server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-zuul
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: /

zuul:
  routes:
    api-a:
      path: /hi/**
      serviceId: service-hi
    api-b:
      path: /other/**
      serviceId: service-other